//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.Authors = new HashSet<Author>();
        }
    
        public string ISBN { get; set; }
        public string Title { get; set; }
        public int EditionNumber { get; set; }
        public string Copyright { get; set; }
    
        public virtual ICollection<Author> Authors { get; set; }
    }
}
